Repository Leafwing-Studios/fonts-of-power, pull requests merged in 2022-10, with the labels that each got.

#76 Update README.md with better directions
  README.md
Labels: documentation

#77 Add script to open rules easily
  open rules.bat
Labels: usability

#94 Weaver review
  docs/src/character-options/classes/weaver/combat_feats.md
  docs/src/character-options/classes/weaver/features.md
  docs/src/character-options/classes/weaver/guild_fabric_of_reality.md
  docs/src/character-options/classes/weaver/powers.md
Labels: design

#108 Prowess should affect max life, rather than basic defense
  docs/src/rules/attributes.md
  docs/src/rules/building-blocks.md
  docs/src/rules/combat/attacking-and-defending.md
  docs/src/rules/resources-and-resting.md
Labels: design

#109 Expertise affects skills known
  docs/src/character-options/character-creation.md
  docs/src/rules/attributes.md
Labels: design

#117 Fix formatting for soulbinder
  docs/src/character-options/classes/soulbinder/features.md
  docs/src/character-options/classes/soulbinder/qualia_backchannel.md
  docs/src/character-options/classes/soulbinder/qualia_distinctive_pulse.md
  docs/src/character-options/classes/soulbinder/qualia_heightened_bond.md
  docs/src/character-options/classes/soulbinder/qualia_soulbound.md
Labels: polish

#118 Fix formatting for ritualist
  docs/src/character-options/classes/ritualist/devotion_augury.md
  docs/src/character-options/classes/ritualist/devotion_consequences.md
  docs/src/character-options/classes/ritualist/features.md
Labels: polish

#122 Format alchemist class
  docs/src/character-options/classes/alchemist/features.md
  docs/src/character-options/classes/alchemist/pursuit_end_product.md
  docs/src/character-options/classes/alchemist/twist_exotic_ingredients.md
  docs/src/character-options/classes/alchemist/twist_secret_ingredient.md
  docs/src/character-options/classes/alchemist/twist_vessel.md
Labels: polish

#123 Rename Ritualist back to Devout
  docs/src/character-options/classes/devout/combat_feats.md
  docs/src/character-options/classes/devout/exploration_feats.md
  docs/src/character-options/classes/devout/features.md
  docs/src/character-options/classes/devout/powers.md
  docs/src/character-options/powers/README.md
  docs/src/rules/combat/tactical-mechanics.md
Labels: worldbuilding
