Repository Leafwing-Studios/fonts-of-power, pull requests merged in 2023-10, with the labels that each got.

#114 Conduit tweaks
  docs/src/character-options/classes/conduit/combat_feats.md
  docs/src/character-options/classes/conduit/features.md
  docs/src/character-options/classes/conduit/power_supply_recharge.md
  docs/src/character-options/classes/conduit/power_supply_siphon.md
Labels: design

#115 Touched tweaks
  docs/src/character-options/classes/touched/coexistence_dynamic.md
  docs/src/character-options/classes/touched/coexistence_synergy.md
  docs/src/character-options/classes/touched/combat_feats.md
  docs/src/character-options/classes/touched/features.md
Labels: design

#116 Incarnation tweaks
  docs/src/character-options/classes/incarnation/combat_feats.md
  docs/src/character-options/classes/incarnation/features.md
  docs/src/character-options/classes/incarnation/temperaments.md
Labels: design

#154 Add trinket rules
  rulebook/src/character-options/gear/README.md
  rulebook/src/rules/combat/acting-in-combat/actions.md
  rulebook/src/worldspeakers/trinkets.md
Labels: design

#158 Card-based turn-order rules
  rulebook/src/rules/combat/round-turns-space.md
Labels: design

#164 Design review: alchemist
  rulebook/src/character-options/classes/alchemist/combat_feats.md
  rulebook/src/character-options/classes/alchemist/exploration_feats.md
  rulebook/src/character-options/classes/alchemist/features.md
  rulebook/src/character-options/classes/conduit/combat_feats.md
  rulebook/src/character-options/feats/exploration-feats.md
  rulebook/src/hacking/class_template/features.md
Labels: design

#168 Add Lifespeaker class
  rulebook/src/SUMMARY.md
  rulebook/src/character-options/classes/_experimental/wildshaper/combat_feats.md
  rulebook/src/character-options/classes/_experimental/wildshaper/exploration_feats.md
  rulebook/src/character-options/classes/_experimental/wildshaper/features.md
  rulebook/src/character-options/classes/_experimental/wildshaper/powers.md
  rulebook/src/character-options/classes/lifespeaker/combat_feats.md
  rulebook/src/character-options/classes/lifespeaker/exploration_feats.md
  rulebook/src/character-options/classes/lifespeaker/features.md
  rulebook/src/character-options/classes/lifespeaker/powers.md
  rulebook/src/character-options/feats/exploration-feats.md
  rulebook/src/character-options/feats/utility-feats.md
Labels: design

#180 Finish Paragon auras
  rulebook/src/character-options/classes/paragon/features.md
  rulebook/src/character-options/classes/paragon/powers.md
Labels: content-idea

#182 Touched class review
  rulebook/src/character-options/classes/touched/combat_feats.md
  rulebook/src/character-options/classes/touched/exploration_feats.md
  rulebook/src/character-options/classes/touched/features.md
  rulebook/src/character-options/feats/exploration-feats.md
Labels: design

#188 Port elementalist to alpha 2
  rulebook/src/character-options/classes/elementalist/combat_feats.md
  rulebook/src/character-options/classes/elementalist/exploration_feats.md
  rulebook/src/character-options/classes/elementalist/features.md
  rulebook/src/character-options/classes/elementalist/powers.md
Labels: design, content-idea

#190 Elementalist tweaks
  rulebook/src/character-options/classes/elementalist/combat_feats.md
  rulebook/src/character-options/classes/elementalist/features.md
Labels: design, balance

#191 Make Lifebreather capstone more interesting
  rulebook/src/character-options/classes/lifespeaker/features.md
Labels: design
